import { jsPDF } from 'jspdf';
import { CostEstimate } from '@/types';

export function generateCSV(estimate: CostEstimate): string {
  const timestamp = new Date().toISOString();
  const headers = [
    'Model',
    'Provider',
    'Input Tokens',
    'Input Cost ($)',
    'Output Tokens',
    'Output Cost ($)',
    'Total Cost ($)',
    'Timestamp'
  ];

  const values = [
    estimate.model.name,
    estimate.model.provider,
    estimate.inputTokens.toString(),
    estimate.inputCost.toFixed(6),
    estimate.outputTokens.toString(),
    estimate.outputCost.toFixed(6),
    estimate.totalCost.toFixed(6),
    timestamp
  ];

  return headers.join(',') + '\n' + values.join(',');
}

export function generatePDF(estimate: CostEstimate): jsPDF {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Cost Estimate', 105, 20, { align: 'center' });

  // Subtitle with timestamp
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128);
  doc.text(`Generated: ${timestamp}`, 105, 28, { align: 'center' });

  // Reset text color
  doc.setTextColor(0);

  // Model Info Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Model Information', 20, 45);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Model: ${estimate.model.name}`, 20, 55);
  doc.text(`Provider: ${estimate.model.provider}`, 20, 63);
  doc.text(`Input Rate: $${estimate.model.inputCostPerMillion} / 1M tokens`, 20, 71);
  doc.text(`Output Rate: $${estimate.model.outputCostPerMillion} / 1M tokens`, 20, 79);

  // Divider
  doc.setDrawColor(200);
  doc.line(20, 88, 190, 88);

  // Cost Breakdown Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Cost Breakdown', 20, 100);

  // Table headers
  const tableStartY = 110;
  doc.setFillColor(245, 245, 245);
  doc.rect(20, tableStartY - 6, 170, 10, 'F');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Type', 25, tableStartY);
  doc.text('Tokens', 80, tableStartY);
  doc.text('Cost', 150, tableStartY);

  // Table rows
  doc.setFont('helvetica', 'normal');

  // Input row
  doc.text('Input', 25, tableStartY + 12);
  doc.text(estimate.inputTokens.toLocaleString(), 80, tableStartY + 12);
  doc.text(`$${estimate.inputCost.toFixed(6)}`, 150, tableStartY + 12);

  // Output row
  doc.text('Output', 25, tableStartY + 22);
  doc.text(estimate.outputTokens.toLocaleString(), 80, tableStartY + 22);
  doc.text(`$${estimate.outputCost.toFixed(6)}`, 150, tableStartY + 22);

  // Divider before total
  doc.setDrawColor(200);
  doc.line(20, tableStartY + 28, 190, tableStartY + 28);

  // Total row
  doc.setFont('helvetica', 'bold');
  doc.text('Total', 25, tableStartY + 38);
  doc.text((estimate.inputTokens + estimate.outputTokens).toLocaleString(), 80, tableStartY + 38);

  // Total cost highlighted
  doc.setFontSize(14);
  doc.text(`$${estimate.totalCost.toFixed(6)}`, 150, tableStartY + 38);

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128);
  doc.text('Generated by AI Cost Estimator', 105, 280, { align: 'center' });

  return doc;
}

export function downloadFile(content: Blob | string, filename: string, mimeType: string): void {
  const blob = typeof content === 'string'
    ? new Blob([content], { type: mimeType })
    : content;

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportAsCSV(estimate: CostEstimate): void {
  const csv = generateCSV(estimate);
  const filename = `cost-estimate-${estimate.model.name.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.csv`;
  downloadFile(csv, filename, 'text/csv');
}

export function exportAsPDF(estimate: CostEstimate): void {
  const doc = generatePDF(estimate);
  const filename = `cost-estimate-${estimate.model.name.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.pdf`;
  doc.save(filename);
}
